package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

/**
 * Dnshosting generated by hbm2java
 */
public class Dnshosting implements java.io.Serializable {
    private Integer id;
    private Domain domain;
    private NameServer nameServer;
    private String type;
    private Boolean allowQuery;
    private Boolean allowUpdate;
    private Boolean allowTransfer;

    public Dnshosting() {}

    public Dnshosting(Domain domain, NameServer nameServer, String type, Boolean allowQuery, Boolean allowUpdate, Boolean allowTransfer) {
        this.domain = domain;
        this.nameServer = nameServer;
        this.type = type;
        this.allowQuery = allowQuery;
        this.allowUpdate = allowUpdate;
        this.allowTransfer = allowTransfer;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Domain getDomain() {
        return this.domain;
    }

    public void setDomain(Domain domain) {
        this.domain = domain;
    }

    public NameServer getNameServer() {
        return this.nameServer;
    }

    public void setNameServer(NameServer nameServer) {
        this.nameServer = nameServer;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Boolean getAllowQuery() {
        return this.allowQuery;
    }

    public void setAllowQuery(Boolean allowQuery) {
        this.allowQuery = allowQuery;
    }

    public Boolean getAllowUpdate() {
        return this.allowUpdate;
    }

    public void setAllowUpdate(Boolean allowUpdate) {
        this.allowUpdate = allowUpdate;
    }

    public Boolean getAllowTransfer() {
        return this.allowTransfer;
    }

    public void setAllowTransfer(Boolean allowTransfer) {
        this.allowTransfer = allowTransfer;
    }
}
