package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * Domain generated by hbm2java
 */
public class Domain implements java.io.Serializable {

    private String domainName;
    private String class_;
    private String adminContact;
    private Integer serial;
    private Integer refresh;
    private Integer retry;
    private Integer expire;
    private Integer ttl;
    private Set<Dnshosting> dnshostings;
    private Set<DomainData> domainData;

    public Domain() {
    }

    public Domain(String domainName) {
        this.domainName = domainName;
    }

    public Domain(String domainName, String class_, String adminContact, Integer serial, Integer refresh, Integer retry, Integer expire, Integer ttl,
            Set<Dnshosting> dnshostings, Set<DomainData> domainData) {
        this.domainName = domainName;
        this.class_ = class_;
        this.adminContact = adminContact;
        this.serial = serial;
        this.refresh = refresh;
        this.retry = retry;
        this.expire = expire;
        this.ttl = ttl;
        this.dnshostings = dnshostings;
        this.domainData = domainData;
    }

    public String getDomainName() {
        return this.domainName;
    }

    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    public String getAdminContact() {
        return this.adminContact;
    }

    public void setAdminContact(String adminContact) {
        this.adminContact = adminContact;
    }

    public Integer getSerial() {
        return this.serial;
    }

    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    public Integer getRefresh() {
        return this.refresh;
    }

    public void setRefresh(Integer refresh) {
        this.refresh = refresh;
    }

    public Integer getRetry() {
        return this.retry;
    }

    public void setRetry(Integer retry) {
        this.retry = retry;
    }

    public Integer getExpire() {
        return this.expire;
    }

    public void setExpire(Integer expire) {
        this.expire = expire;
    }

    public Integer getTtl() {
        return this.ttl;
    }

    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }

    /**
     * @return the dnshostings
     */
    public Set<Dnshosting> getDnshostings() {
        return dnshostings;
    }

    /**
     * @param dnshostings the dnshostings to set
     */
    public void setDnshostings(Set<Dnshosting> dnshostings) {
        this.dnshostings = dnshostings;
    }

    /**
     * @return the domainData
     */
    public Set<DomainData> getDomainData() {
        return domainData;
    }

    /**
     * @param domainData the domainData to set
     */
    public void setDomainData(Set<DomainData> domainData) {
        this.domainData = domainData;
    }
}
