package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

/**
 * DomainData generated by hbm2java
 */
public class DomainData implements java.io.Serializable {

    private Integer id;
    private Domain domain;
    private ResourceRecord resourceRecord;

    public DomainData() {
    }

    public DomainData(Integer id, Domain domain, ResourceRecord resourceRecord) {
        this.id = id;
        this.domain = domain;
        this.resourceRecord = resourceRecord;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the domain
     */
    public Domain getDomain() {
        return domain;
    }

    /**
     * @param domain the domain to set
     */
    public void setDomain(Domain domain) {
        this.domain = domain;
    }

    /**
     * @return the resourceRecord
     */
    public ResourceRecord getResourceRecord() {
        return resourceRecord;
    }

    /**
     * @param resourceRecord the resourceRecord to set
     */
    public void setResourceRecord(ResourceRecord resourceRecord) {
        this.resourceRecord = resourceRecord;
    }
}
