package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * Ipaddress generated by hbm2java
 */
public class Ipaddress implements java.io.Serializable {

    private Integer id;
    private String version;
    private String address;
    private String type;
    private Subnet subnet;
    private Set<Ipassignment> ipAssignments;

    public Ipaddress() {
    }

    public Ipaddress(String address) {
        this.address = address;
    }

    public Ipaddress(String address, String type, Subnet subnet) {
        this.address = address;
        this.type = type;
        this.subnet = subnet;
    }
    
    public Ipaddress(Integer id, String address, String version, String type){
        this.id = id;
        this.address = address;
        this.version = version;
        this.type = type;
    }
    
    public Ipaddress(String address, String type, Subnet subnet, 
            Set<Ipassignment> ipAssignments) {
        this.address = address;
        this.type = type;
        this.subnet = subnet;
        this.ipAssignments = ipAssignments;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Subnet getSubnet() {
        return this.subnet;
    }

    public void setSubnet(Subnet subnet) {
        this.subnet = subnet;
    }

    /**
     * @return the ipAssignments
     */
    public Set<Ipassignment> getIpAssignments() {
        return ipAssignments;
    }

    /**
     * @param ipAssignments the ipAssignments to set
     */
    public void setIpAssignments(Set<Ipassignment> ipAssignments) {
        this.ipAssignments = ipAssignments;
    }
}
