package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * NameServer generated by hbm2java
 */
public class NameServer implements java.io.Serializable {
    private String hostname;
    private Integer ttl;
    private String class_;
    private String ipAddress;
    private Set<Dnshosting> dnshostings;

    public NameServer() {
    }

    public NameServer(String hostname) {
        this.hostname = hostname;
    }

    public NameServer(String hostname, Integer ttl, String class_, String ipAddress) {
        this.hostname = hostname;
        this.ttl = ttl;
        this.class_ = class_;
        this.ipAddress = ipAddress;
    }

    public NameServer(String hostname, Integer ttl, String class_, String ipAddress,
            Set<Dnshosting> dnshostings) {
        this.hostname = hostname;
        this.ttl = ttl;
        this.class_ = class_;
        this.ipAddress = ipAddress;
        this.dnshostings = dnshostings;
    }

    public String getHostname() {
        return this.hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public Integer getTtl() {
        return this.ttl;
    }

    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    public String getIpAddress() {
        return this.ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * @return the dnshostings
     */
    public Set<Dnshosting> getDnshostings() {
        return dnshostings;
    }

    /**
     * @param dnshostings the dnshostings to set
     */
    public void setDnshostings(Set<Dnshosting> dnshostings) {
        this.dnshostings = dnshostings;
    }
}
