package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * Network generated by hbm2java
 */
public class Network implements java.io.Serializable {

    private Integer id;
    private String version;
    private String networkAddr;
    private String netname;
    private Set<Subnet> subnets;

    public Network() {
    }

    public Network(String networkAddr, String netname) {
        this.networkAddr = networkAddr;
        this.netname = netname;
    }

    public Network(Integer id, String version, String networkAddr, String netname,
            Set<Subnet> subnets) {
        this.id = id;
        this.version = version;
        this.networkAddr = networkAddr;
        this.netname = netname;
        this.subnets = subnets;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getNetworkAddr() {
        return this.networkAddr;
    }

    public void setNetworkAddr(String networkAddr) {
        this.networkAddr = networkAddr;
    }

    public String getNetname() {
        return this.netname;
    }

    public void setNetname(String netname) {
        this.netname = netname;
    }

    /**
     * @return the subnets
     */
    public Set<Subnet> getSubnets() {
        return subnets;
    }

    /**
     * @param subnets the subnets to set
     */
    public void setSubnets(Set<Subnet> subnets) {
        this.subnets = subnets;
    }
}
