package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;


/**
 * ResourceRecord generated by hbm2java
 */
public class ResourceRecord implements java.io.Serializable {

    private Integer id;
    private String resourceRecordType;
    private Integer ttl;
    private String hostname;
    private String classOfData;
    private Set<DomainData> domainData;

    public ResourceRecord() {
    }

    public ResourceRecord(String resourceRecordType) {
        this.resourceRecordType = resourceRecordType;
    }

    public ResourceRecord(String resourceRecordType, Integer ttl,
            String hostname, String classOfData, Set<DomainData> domainData) {
        this.resourceRecordType = resourceRecordType;
        this.ttl = ttl;
        this.hostname = hostname;
        this.classOfData = classOfData;
        this.domainData = domainData;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getResourceRecordType() {
        return this.resourceRecordType;
    }

    public void setResourceRecordType(String resourceRecordType) {
        this.resourceRecordType = resourceRecordType;
    }

    public Integer getTtl() {
        return this.ttl;
    }

    public void setTtl(Integer ttl) {
        this.ttl = ttl;
    }

    public String getHostname() {
        return this.hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public String getClassOfData() {
        return this.classOfData;
    }

    public void setClassOfData(String classOfData) {
        this.classOfData = classOfData;
    }

    /**
     * @return the domainData
     */
    public Set<DomainData> getDomainData() {
        return domainData;
    }

    /**
     * @param domainData the domainData to set
     */
    public void setDomainData(Set<DomainData> domainData) {
        this.domainData = domainData;
    }
}
