package hibernatepojos;
// Generated Feb 11, 2013 5:20:48 PM by Hibernate Tools 3.2.1.GA

import java.util.Set;

/**
 * Subnet generated by hbm2java
 */
public class Subnet implements java.io.Serializable {
    private Integer id;
    private String subname;
    private String subnetMask;
    private String location;
    private String subnetAddr;
    private Set<Ipaddress> ipAddresses;
    private Network network;

    public Subnet() {}

    public Subnet(String subname, String subnetMask, String location, String subnetAddr, Network network) {
        this.subname = subname;
        this.subnetMask = subnetMask;
        this.location = location;
        this.subnetAddr = subnetAddr;
        this.network = network;
    }

    public Subnet(String subname, String subnetMask, String location,
            String subnetAddr, Network network, Set<Ipaddress> ipAddresses) {
        this.subname = subname;
        this.subnetMask = subnetMask;
        this.location = location;
        this.subnetAddr = subnetAddr;
        this.network = network;
        this.ipAddresses = ipAddresses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSubname() {
        return this.subname;
    }

    public void setSubname(String subname) {
        this.subname = subname;
    }

    public String getSubnetMask() {
        return this.subnetMask;
    }

    public void setSubnetMask(String subnetMask) {
        this.subnetMask = subnetMask;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getSubnetAddr() {
        return this.subnetAddr;
    }

    public void setSubnetAddr(String subnetAddr) {
        this.subnetAddr = subnetAddr;
    }

    public Network getNetwork() {
        return this.network;
    }

    public void setNetwork(Network network) {
        this.network = network;
    }

    /**
     * @return the ipAddresses
     */
    public Set<Ipaddress> getIpAddresses() {
        return ipAddresses;
    }

    /**
     * @param ipAddresses the ipAddresses to set
     */
    public void setIpAddresses(Set<Ipaddress> ipAddresses) {
        this.ipAddresses = ipAddresses;
    }
}
